version: '3'
services:
  postgresDB:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456789
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@localhost
      - PGADMIN_DEFAULT_PASSWORD=123456789
    depends_on:
      - postgresDB
    networks:
      - postgres-network
    container_name: postgresDB

networks:
  postgres-network:
    driver: bridge